# Generated by Django 4.2.16 on 2024-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WHThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('entity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сущность')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('review_rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг отзывов')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик')),
                ('supplier_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID поставщика')),
                ('supplier_rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг поставщика')),
                ('product_id', models.CharField(max_length=255, unique=True, verbose_name='ID товара')),
                ('price_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая цена')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Доступно на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
